name: build bot module

on:
  push:
    branches: [ "master", "hw**" ]
    paths: [ "pom.xml", "bot/**", "common/**"]
  pull_request:
    branches: [ "master", "hw**" ]
    paths: [ "pom.xml", "bot/**", "common/**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.6'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -pl bot -am
