name: build scrapper module
    
on:
  workflow_dispatch:
  push:
    branches: [ "master", "hw**" ]
    paths: [ "pom.xml", "scrapper/**", "common/**", "link-parser/**", ".github/workflows/scrapper.yml"]
  pull_request:
    branches: [ "master", "hw**" ]
    paths: [ "pom.xml", "scrapper/**", "common/**", "link-parser/**"]

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: hw9.2-3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.6'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -pl scrapper -am
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: See directory
      run: ls -la
    - name: See scrapper
      run: ls -la scrapper
    - name: Build Docker image
      run: docker build -t ${{ env.REGISTRY }}/scrapper:latest -f scrapper/scrapper.Dockerfile .
    - name: Push Docker image to GitHub Packages
      run: docker push ${{ env.REGISTRY }}/scrapper:latest
