name: build scrapper module
    
on:
  workflow_dispatch:
  push:
    branches: [ "master", "hw**" ]
    paths: [ "pom.xml", "scrapper/**", "common/**", "link-parser/**", ".github/workflows/scrapper.yml"]
  pull_request:
    branches: [ "master", "hw**" ]
    paths: [ "pom.xml", "scrapper/**", "common/**", "link-parser/**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.6'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -pl scrapper -am
