name: build scrapper module

on:
  workflow_dispatch:
  push:
    paths: [ "pom.xml", "checkstyle.xml", "scrapper/**", "common/**", "link-parser/**", ".github/workflows/scrapper.yml"]
  pull_request:
    paths: [ "pom.xml", "checkstyle.xml", "scrapper/**", "common/**", "link-parser/**"]

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.6'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -pl scrapper -am
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: docker build -t ${{ env.REGISTRY }}/vladimirzaitsev21/scrapper:latest -f scrapper/scrapper.Dockerfile .
    - name: Push Docker image to GitHub Packages
      run: docker push ${{ env.REGISTRY }}/vladimirzaitsev21/scrapper:latest

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.6'
          distribution: 'temurin'
          cache: maven
      - name: Run checkstyle with Maven
        run: mvn -pl scrapper -am checkstyle:check -Dcheckstyle.config.location=checkstyle.xml
